# Site settings
title: /dav/random
email: 
description: > # this means to ignore newlines until "baseurl:"
    some of my randomness
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dav_random
github_username:  davrandom

# Build settings
markdown: kramdown
