# Site settings
title: /dav/random

description: > # this means to ignore newlines until "baseurl:"
    some of my randomness
baseurl: "" # the subpath of your site, e.g. /blog/
paginate_path: "blog/page:num/"
permalink: blog/:title/
tag_permalink_style: pretty
url: "http://scaini.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
    input: GFM
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Moto
   url: /moto.html
 - title: Archive
   url: /archive.html
 - title: Tags
   url: /tags/index.html
 
social:
    twitter: dav_random
    github:  davrandom

tag_page_layout: tag_page
tag_page_dir: tag
