# Site settings
title: /dav/random

description: > # this means to ignore newlines until "baseurl:"
    some of my randomness
baseurl: "" # the subpath of your site, e.g. /blog/
paginate_path: "blog/page:num/"
permalink: blog/:title/
url: "http://scaini.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 
social:
    twitter: dav_random
    github:  davrandom


